### ISSUE TITLE
Custom framework and exceptions sharing

### ISSUE THREAD

**Issue by mgalesloot** [kubescape/headlamp-plugin#11]
###  Custom Frameworks and Exception Policies

The Kubescape Headlamp plugin enables teams to create custom frameworks and exception policies, allowing for tailored compliance checks to meet specific needs and requirements.

### Exporting Frameworks and Exceptions

Frameworks and exceptions can be exported from Headlamp as JSON documents, which can be used with the Kubescape command-line tool.

### Sharing Frameworks and Exceptions

To facilitate sharing between Headlamp users, frameworks and exceptions will be stored as ConfigMaps in the Kubescape namespace. When Headlamp is configured to view multiple clusters, these objects can also be shared across clusters.

### Identifying ConfigMaps

The name of the ConfigMap is the name of the object followed by a random string. This naming convention allows for unique identification of ConfigMaps while still maintaining a clear connection to the original object name.

To identify ConfigMaps, the following labels will be used:

Frameworks: `kubescape.io/custom-object: framework` 
Exceptions: `kubescape.io/custom-object: exceptions` 

### Examples 

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    kubescape.io/custom-object: framework
  name: dev-framework-rbkcz8
  namespace: kubescape
data:
  name: dev
  controlsIDs: '["C-0002", "C-0003"]'
  description: "Dev framework"
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: dev
    kubescape.io/custom-object: exceptions
  name: dev-exceptions-rwu4sv
  namespace: kubescape2
data:
  name: dev
  exceptionPolicies: |
    [
     {
        "name":"resource-exceptions",
        "creationTime":"2025-05-13T07:06:55.570Z",
        "resources":[
           {
              "designatorType":"Attributes",
              "attributes":{
                 "name":"headlamp",
                 "namespace":"headlamp",
                 "kind":"Deployment"
              }
           }
        ]
     },
     {
        "name":"namespace-cert-manager-exception",
        "creationTime":"2025-05-13T07:06:58.506Z",
        "resources":[
           {
              "designatorType":"Attributes",
              "attributes":{
                 "namespace":"cert-manager"
              }
           }
        ]
     }
    ]
```
